### ISSUE TITLE
Failed to connect to updates.counterplay.co

### ISSUE THREAD

**Issue by arman00** [mycroft92/duelyst_linux#1]
Hello, thanks for sharing this script! I couldn't manage to install it though. Looks like it cannot download some files, saying Failed to connect to updates.counterplay.co with the curl command, at the first line of the script. Would be great if you have a solution to fix this!

**Comment by mycroft92** [comment]
Hi @arman00 , apologies for the delayed response. The script is currently not functional because after the Bandai Namco deal, the source code access is closed and you only get the code through their launcher. I cannot figure out the current download URL and hence the curl command failure. If you can figure it out, I'd be happy to fix and test it out.
